name: job-matrix

on:
  push:
    paths:
      - '07-job-matrix/**'
      - '.github/workflows/07-job-matrix.yml'
    
jobs:
  my-job:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-22.04]
        node: [ 14, 16]
        exclude:
        - os: ubuntu-22.04
          node: 12

    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          
      - name: Print work dir
        run: echo "[$(pwd)]"
          
      - name: Print repo name
        run: echo "repo name [${{ github.event.repository.name }}]"
            
      - name: Print github.event.inputs
        env:
          STEPS_CONTEXT: ${{ toJson(github.event.inputs) }}
        run: echo "$STEPS_CONTEXT"
          
      - name: Print OS-release
        run: cat /etc/os-release
        
      - name: Run tests
        working-directory: ./07-job-matrix
        run: npm test
        
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3.11

      # Your steps to generate the output file or result
      - name: Generate output file
        run: echo "This is some output" > output.txt
        
      # Save the file as an artifact
      - name: Save output as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: output.txt
